# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.9.10-hotspot
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.21.11-v1.1.0-beta
maven_group=org.KViEternal
archives_base_name=Combat-Maid-Mod

# Dependencies
fabric_version=0.141.4+1.21.11

